### ISSUE TITLE
Wrong reference genome indicated in the juicer.log

### ISSUE THREAD

**Issue by Audald** [ArimaGenomics/Juicer_pipeline_containers#1]
Hi there,

Thanks for setting up the latest version of the Juicer singularity. I am running the image as follows (as reported by the `aligned/header` file):

`Experiment description: Juicer version 1.6; BWA 0.7.17-r1188; 20 threads; openjdk version "11.0.19" 2023-04-18; /opt/scripts/juicer.sh -d /path/to/folder -D /opt/ -p /path/to/folder/ref/clean.chrom.sizes -y /path/to/folder/ref/sites.txt -z /path/to/folder/ref/genome.fasta -t 20`

However, the `juicer.log` indicates that I am aligning my reads against the `hg19` genome.

```
(-: Looking for fastq files...fastq files exist
(-: Aligning files matching /path/to/folder/fastq/*_R*.fastq* to genome hg19 with site file /path/to/folder/ref/sites.txt
(-: Created /path/to/folder/splits and /path/to/folder/aligned.
```

I suspect this is a bug/error because when I try to force the mapping to `hg19` (instead of my `-z genome.fasta`) with `-g hg19`:

`Reference sequence /opt//references/homo_sapiens_assembly19.fasta does not exist` (as expected)

Could you please confirm that this is indeed a bug with the report (rather than actually aligning my reads against `hg19`) and whether this is a problem with this image or I should rather raise that to the Juicer developers at the Aiden Lab?

Thank you!

**Comment by xz-000** [comment]
Hi Audald,

You are correct! This is indeed a bug with the report only. Your mapping will be correctly mapped to the reference genome in the command-line option you provided.
This is a historical issue in the Juicer pipeline internally. I could not fix it without modifying the Juicer pipeline. It is not too difficult to change the Juicer pipeline script, but i think it would be better for the developers from the Aiden group to update this in their pipeline.

Best,
Arima Technical Support Team

**Comment by Audald** [comment]
Thanks for your confirmation @XiangArima!
I have created an issue for the Aiden lab to fix it: https://github.com/aidenlab/juicer/issues/364
